name: bPChat
version: '${project.version}'
main: me.bloone.bPChat
api-version: 1.18
authors: [ bloone ]
description: A simple chat plugin.
commands:
  bpchat:
    description: Main command.
    usage: /<command>
    aliases: [chat]
  mute:
    description: Mute someone. Silent.
    usage: /<command> <online player> <not required, reason>
  unmute:
    description: Unmute someone.
    usage: /<command> <player>

permissions:
  bpchat.*:
    description: All permissions. You are the power.
    default: op
    children:
      bpchat.command.main: true
      bpchat.command.reload: true
  bpchat.command.main:
    description: Allows you to use /bpchat command.
    default: op
  bpchat.command.reload:
    description: Allows you to use /bpchat reload command.
    default: op
  bpchat.command.mute:
    description: Allows you to use /mute command. Silent, please.
    default: op
  bpchat.command.unmute:
    description: Allows you to use /unmute command. Ok, now you can speak.
    default: op